name: Run Promoter Buying Scraper Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # This means every 5 minutes (UTC time)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Tijori from local wheel
        run: pip install tijori-0.1.0-py2.py3-none-any.whl

      - name: Install other dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

